name: EMToolkit_env_minimal
channels:
  - defaults
dependencies:
  - python>=3.10
  - pip
  - pip:
    - astropy>=6.1.1
    - scipy>=1.10.1
    - ipympl>=0.9.4
    - ndcube>=2.2.2
    - xrtpy>=0.4.0
    - sunpy>=4.1.5
    - aiapy
    - lxml
    - drms>=0.7.1
    - zeep>=4.1.0